"""
    Organisations Service

    A set of API endpoints that allow you to get information about organizations  # noqa: E501

    The version of the OpenAPI document: 1.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_organisation_sdk
from osis_organisation_sdk.model.address import Address
globals()['Address'] = Address
from osis_organisation_sdk.model.paginated_addresses_all_of import PaginatedAddressesAllOf


class TestPaginatedAddressesAllOf(unittest.TestCase):
    """PaginatedAddressesAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedAddressesAllOf(self):
        """Test PaginatedAddressesAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedAddressesAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
