"""
    Organisations Service

    A set of API endpoints that allow you to get information about organizations  # noqa: E501

    The version of the OpenAPI document: 1.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_organisation_sdk
from osis_organisation_sdk.model.entite_type_enum import EntiteTypeEnum
globals()['EntiteTypeEnum'] = EntiteTypeEnum
from osis_organisation_sdk.model.entite import Entite


class TestEntite(unittest.TestCase):
    """Entite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntite(self):
        """Test Entite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Entite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
