"""
    Organisations Service

    A set of API endpoints that allow you to get information about organizations  # noqa: E501

    The version of the OpenAPI document: 1.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_organisation_sdk
from osis_organisation_sdk.model.entite import Entite
globals()['Entite'] = Entite
from osis_organisation_sdk.model.paginated_entites_all_of import PaginatedEntitesAllOf


class TestPaginatedEntitesAllOf(unittest.TestCase):
    """PaginatedEntitesAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedEntitesAllOf(self):
        """Test PaginatedEntitesAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedEntitesAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
