"""
    Organisations Service

    A set of API endpoints that allow you to get information about organizations  # noqa: E501

    The version of the OpenAPI document: 1.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_organisation_sdk
from osis_organisation_sdk.model.paging import Paging


class TestPaging(unittest.TestCase):
    """Paging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaging(self):
        """Test Paging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Paging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
