# flake8: noqa

"""
    Organisations Service

    A set of API endpoints that allow you to get information about organizations  # noqa: E501

    The version of the OpenAPI document: 1.3
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.3"

# import ApiClient
from osis_organisation_sdk.api_client import ApiClient

# import Configuration
from osis_organisation_sdk.configuration import Configuration

# import exceptions
from osis_organisation_sdk.exceptions import OpenApiException
from osis_organisation_sdk.exceptions import ApiAttributeError
from osis_organisation_sdk.exceptions import ApiTypeError
from osis_organisation_sdk.exceptions import ApiValueError
from osis_organisation_sdk.exceptions import ApiKeyError
from osis_organisation_sdk.exceptions import ApiException
